### ISSUE TITLE
Color schemes

### ISSUE THREAD

**Issue by foamy-latte** [cpuabuse/cards.js#1]
# Task

## Goals

- [x] Decide on the common color purposes/functions - e.g. `$primaryColor`, `$secondaryColor` etc.
- [x] Design a couple of color schemes that satisfy the color purposes
- [x] Create and populate YAML files with the schemes

## Useful links

* [HTML Color Names](https://www.w3schools.com/colors/colors_names.asp)
* [Color Wheel](https://color.adobe.com/)

**Comment by foamy-latte** [comment]
Closing the task, completed with the following commits:

* 4bef844
* 0b612f1
* e427165
* 47d56c1
