### ISSUE TITLE
Sass demo

### ISSUE THREAD

**Issue by foamy-latte** [cpuabuse/cards.js#2]
# Task

## Goals

Create a sass file prototype.

## Todo

- [ ] Make a proper html file, containing arrangement(not necessarily all) of following tags:
   * `<form>`
   * `<section>`
   * `<ul>`
   * `<li>`
   * `<h1>`
   * `<h2>`
   * `<button>`
   * `<a>`
   * `<nav>`
- [ ] Create and apply the the css based on the color scheme to that html, so it will be beautiful
- [ ] Create an scss file, that should generated a css with an identical behavior

## Useful URLs
[Sass reference](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#css_extensions)
[Sass to css](https://www.sassmeister.com/)
