### ISSUE TITLE
Get resource by path

### ISSUE THREAD

**Issue by foamy-latte** [cpuabuse/cards.js#3]
# Task

## Goals

Write a function, to match path with resource. Feel free to use abstractions. Utilize your understanding of existing infrastructure, and planned infrastructure.

```javascript
class App extends System{
	getResourceByPath(path, resourceArray){
		/*
			...
		*/

		return resource;
	}
}
```

### Note

**From within getResourceByPath**

* Resources can be retrieved as: ```this.resources[resourceKey]```
* Path-to-resource array can be accessed at: ```this.paths```

## Todo

- [x] Outline the function
- [x] Write the function
- [x] Think how the functionality could be extended, or made better and apply that
- [x] Check that commentary is rich

**Comment by Gabriele-Gentile** [comment]
Issue resolved.
